name: Build Goiás RolePlay Godot APK

on:
  workflow_dispatch:
  push:
    paths:
      - 'game3d/**'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.5.1
          use-dotnet: false

      - name: Verificar arquivos
        run: |
          echo "Projeto:"
          ls -la game3d
          echo "Workflow:"
          ls -la .github/workflows

      - name: Verificar projeto Godot
        run: |
          godot --headless \
            --path game3d \
            --editor \
            --quit

      - name: Criar saída
        run: mkdir -p game3d/build

      - name: Exportar Android
        run: |
          godot --headless \
            --path game3d \
            --export-debug "Android" \
            build/goias-roleplay.apk

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: GoiasRP-Godot-APK
          path: game3d/build/goias-roleplay.apk
