name: Build Goiás RolePlay Godot APK

on:
  workflow_dispatch:
  push:
    paths:
      - 'game3d/**'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.5.1
          use-dotnet: false

      - name: Instalar templates Android do Godot
        run: |
          mkdir -p "$HOME/.local/share/godot/export_templates/4.5.1.stable"

          wget -O /tmp/templates.tpz \
            https://github.com/godotengine/godot/releases/download/4.5.1-stable/Godot_v4.5.1-stable_export_templates.tpz

          unzip -q /tmp/templates.tpz -d /tmp/godot-templates

          find /tmp/godot-templates -type f -name "android_debug.apk" \
            -exec cp {} "$HOME/.local/share/godot/export_templates/4.5.1.stable/" \;

          find /tmp/godot-templates -type f -name "android_release.apk" \
            -exec cp {} "$HOME/.local/share/godot/export_templates/4.5.1.stable/" \;

      - name: Verificar templates
        run: |
          ls -lh "$HOME/.local/share/godot/export_templates/4.5.1.stable/"

      - name: Criar pasta de saída
        run: mkdir -p game3d/build

            - name: Exportar APK
        run: |
          godot --headless \
            --path game3d \
            --verbose \
            --export-debug "Android" \
            build/goias-roleplay.apk

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: GoiasRP-Godot-APK
          path: game3d/build/goias-roleplay.apk
